### ISSUE TITLE
Editing Chinese text no longer works

### ISSUE THREAD

**Issue by matchachoco95** [tls-kr/tls-app#99]
**Describe the bug**
When I tried to edit a line of Chinese text in the 算數書 via the lock symbol on the right side, something strange happened: a window popped up asking me to enter my log-in data (despite my already being logged in), and even when I did so, I could not edit the text as clicking on the lock symbol once more did not do anything. This is a very recent issue as I edited numerous lines of texts only days ago. Here is a screenshot of the pop-up window:
![Textbearbeitung](https://user-images.githubusercontent.com/116962137/211157467-8e938e99-d2aa-476f-bfe8-5fc0aee05234.png)

**To Reproduce**
1. Go to any text. (I tried another one as well to see if it was only an issue for the 算數書 - it was not.) 
2. Highlight the line that you would like to edit. 
3. Click on the lock symbol popping up alongside the other features.

**Expected behavior**
It would like to be able to edit Chinese text like before.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser [e.g. chrome, safari]: I tried both Google Chrome and Firefox.

**Comment by cwittern** [comment]
I tried to reproduce the problem, but could not do so, even logging in with your account and editing this exact same text.  So either it was a transient problem, which sorted out itself, or I accidentally broke something and also accidentally fixed it later (this does happen sometimes...).  So please check again and see if the problem persists on your side.
One piece of general advice:  If something like this happens, a first line of defense is to restart the browser and see if the problem persists.  Sometimes problems are caused by changes on the server only partially making it to the browser (the browser does cache some files that usually do not change for efficiency and might fail to notice when they actually did change).

**Comment by matchachoco95** [comment]
It does seem to be working again for me as well! Maybe it was a problem with my browser after all, or as you said, the problem got fixed on the side. Either way, as long as it's working again, all is well. Thank you!
